[project]
id = "palate"

[api]
port = 54321
schemas = ["public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
major_version = 15

[studio]
port = 54323

[auth]
site_url = "palate://auth-callback"
additional_redirect_urls = ["palate://auth-callback"]

[auth.external.apple]
enabled = true

[auth.external.google]
enabled = true
